apiVersion: lambda.aws.amazon.com/v1alpha1
kind: MicroVMImage
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  source:
    s3Bucket: ${S3_BUCKET}
    s3Key: ${S3_KEY}
  baseImageArn: "${BASE_IMAGE_ARN}"
  buildRoleArn: "${BUILD_ROLE_ARN}"
