apiVersion: lambda.aws.amazon.com/v1alpha1
kind: MicroVMNetwork
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  subnetIds:
    - ${SUBNET_1}
    - ${SUBNET_2}
  securityGroupIds:
    - ${SG_ID}
  operatorRoleArn: "${OPERATOR_ROLE}"
