apiVersion: lambda.aws.amazon.com/v1alpha1
kind: MicroVMClass
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  maxIdleDurationSeconds: 900
  suspendedDurationSeconds: 1800
  description: "UAT admission test class"
