apiVersion: lambda.aws.amazon.com/v1alpha1
kind: MicroVM
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  imageRef: nonexistent-image-that-will-never-resolve
  desiredState: Running
  maxIdleDurationSeconds: 900
  suspendedDurationSeconds: 1800
