apiVersion: lambda.aws.amazon.com/v1alpha1
kind: MicroVMReplicaSet
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: ${REPLICAS}
  template:
    imageRef: ${IMAGE_REF}
    maxIdleDurationSeconds: 600
    suspendedDurationSeconds: 900
