apiVersion: lambda.aws.amazon.com/v1alpha1
kind: MicroVM
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  imageRef: ${IMAGE_REF}
  desiredState: Running
  maxIdleDurationSeconds: 900
  suspendedDurationSeconds: 1800
  ingressNetworkConnectors:
    - "arn:aws:lambda:${REGION}:aws:network-connector:aws-network-connector:ALL_INGRESS"
  egressNetworkConnectors:
    - "arn:aws:lambda:${REGION}:aws:network-connector:aws-network-connector:INTERNET_EGRESS"
