apiVersion: lambda.aws.amazon.com/v1alpha1
kind: MicroVM
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  imageRef: ${IMAGE_REF}
  desiredState: Running
  maxIdleDurationSeconds: ${MAX_IDLE}
  suspendedDurationSeconds: ${SUSPENDED_DURATION}
  autoResumeEnabled: ${AUTO_RESUME}
